services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: missions
      POSTGRES_DB: missions
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:missions@db:5432/missions?sslmode=disable
    command: ./mission-api

volumes:
  pgdata:
